let client_finish_table = [
    {
        "EDTA": 33,
        "ESR": 11,
        "Plasma": 22,
        "SST": 77,
        "Urine": 11,
        "address": "",
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "",
        "index": 34,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "2016-09-30 17-30-31",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": "2016-08-20 17-30-31"
    },
    {
        "EDTA": 33,
        "ESR": 11,
        "Plasma": 22,
        "SST": 77,
        "Urine": 11,
        "address": "",
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "11",
        "index": 35,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "2016-09-30 17-30-31",
        "regular_box": null,
        "req": 11,
        "shipping_method": "Ground",
        "time": "2016-08-20 17-31-58"
    },
    {
        "EDTA": 13,
        "ESR": 11,
        "Plasma": 12,
        "SST": 37,
        "Urine": 11,
        "address": "",
        "big_box": 1,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "",
        "index": 36,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "2016-09-30 17-30-31",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": "2016-08-20 17-44-38"
    },
    {
        "EDTA": 0,
        "ESR": 0,
        "Plasma": 0,
        "SST": 1,
        "Urine": 0,
        "address": "",
        "big_box": null,
        "client_id": 2100,
        "client_practice_name": "Health and Wellness Center",
        "comments": "2",
        "index": 38,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "2016-09-30 17-30-31",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": "2016-09-20 12-37-22"
    },
    {
        "EDTA": 2,
        "ESR": 2,
        "Plasma": 2,
        "SST": 5,
        "Urine": 2,
        "address": "",
        "big_box": 3,
        "client_id": 1500,
        "client_practice_name": "Arizona Digestive Health",
        "comments": "gfgf",
        "index": 39,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "2016-09-30 17-30-31",
        "regular_box": null,
        "req": 10,
        "shipping_method": "2day",
        "time": "2016-09-20 13-09-41"
    }
];

export default client_finish_table;