let client_pending_table = [
    {
        "EDTA": null,
        "ESR": null,
        "Plasma": null,
        "SST": 2,
        "Urine": null,
        "address": null,
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": null,
        "id": 2,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": null,
        "time": ""
    },
    {
        "EDTA": null,
        "ESR": null,
        "Plasma": null,
        "SST": 2,
        "Urine": null,
        "address": null,
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": null,
        "id": 3,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": null,
        "time": ""
    },
    {
        "EDTA": null,
        "ESR": null,
        "Plasma": null,
        "SST": 2,
        "Urine": null,
        "address": null,
        "big_box": null,
        "client_id": 1234,
        "client_practice_name": "Shawn Michael Field MD PhD LLC",
        "comments": null,
        "id": 4,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": null,
        "time": ""
    },
    {
        "EDTA": null,
        "ESR": null,
        "Plasma": null,
        "SST": 2,
        "Urine": null,
        "address": null,
        "big_box": null,
        "client_id": 1234,
        "client_practice_name": "Shawn Michael Field MD PhD LLC",
        "comments": null,
        "id": 5,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": null,
        "time": ""
    },
    {
        "EDTA": null,
        "ESR": null,
        "Plasma": null,
        "SST": 2,
        "Urine": null,
        "address": null,
        "big_box": null,
        "client_id": 1234,
        "client_practice_name": "Shawn Michael Field MD PhD LLC",
        "comments": null,
        "id": 6,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": null,
        "time": ""
    },
    {
        "EDTA": 1,
        "ESR": 0,
        "Plasma": 0,
        "SST": 2,
        "Urine": 0,
        "address": "",
        "big_box": 1,
        "client_id": 1500,
        "client_practice_name": "Arizona Digestive Health",
        "comments": "test",
        "id": 13,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": 2,
        "shipping_method": "2day",
        "time": ""
    },
    {
        "EDTA": 1,
        "ESR": 0,
        "Plasma": 0,
        "SST": 2,
        "Urine": 0,
        "address": "",
        "big_box": 1,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "ff",
        "id": 14,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": 1,
        "shipping_method": "2day",
        "time": ""
    },
    {
        "EDTA": 0,
        "ESR": 0,
        "Plasma": 0,
        "SST": 1,
        "Urine": 0,
        "address": "",
        "big_box": 1,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "11",
        "id": 15,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": 1,
        "req": 1,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 0,
        "ESR": 0,
        "Plasma": 0,
        "SST": 1,
        "Urine": 0,
        "address": "",
        "big_box": 1,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "1",
        "id": 16,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": 1,
        "req": 1,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 111,
        "ESR": 1,
        "Plasma": 11,
        "SST": 1222,
        "Urine": 1,
        "address": "",
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "11",
        "id": 17,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": 1,
        "req": 1,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 1,
        "ESR": 0,
        "Plasma": 0,
        "SST": 12,
        "Urine": 0,
        "address": "",
        "big_box": 1,
        "client_id": 1500,
        "client_practice_name": "Arizona Digestive Health",
        "comments": "1",
        "id": 18,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": 1,
        "shipping_method": "overnight",
        "time": ""
    },
    {
        "EDTA": 1212,
        "ESR": 0,
        "Plasma": 0,
        "SST": 12122424,
        "Urine": 0,
        "address": "",
        "big_box": 1,
        "client_id": 1500,
        "client_practice_name": "Arizona Digestive Health",
        "comments": "",
        "id": 19,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": 1,
        "shipping_method": "2day",
        "time": ""
    },
    {
        "EDTA": 1111,
        "ESR": 0,
        "Plasma": 11,
        "SST": 112222,
        "Urine": 0,
        "address": "",
        "big_box": 1,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "",
        "id": 20,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 2,
        "ESR": 0,
        "Plasma": 0,
        "SST": 14,
        "Urine": 0,
        "address": "",
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "",
        "id": 21,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 11,
        "ESR": 0,
        "Plasma": 0,
        "SST": 1122,
        "Urine": 0,
        "address": "",
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "",
        "id": 22,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 11,
        "ESR": 0,
        "Plasma": 0,
        "SST": 22,
        "Urine": 0,
        "address": "",
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "",
        "id": 23,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 11,
        "ESR": 11,
        "Plasma": 11,
        "SST": 22,
        "Urine": 11,
        "address": "",
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "",
        "id": 24,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 111111,
        "ESR": 11,
        "Plasma": 1111,
        "SST": 11222222,
        "Urine": 11,
        "address": "",
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "",
        "id": 25,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 111111,
        "ESR": 11,
        "Plasma": 1111,
        "SST": 11222222,
        "Urine": 11,
        "address": "",
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "",
        "id": 26,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 11,
        "ESR": 0,
        "Plasma": 0,
        "SST": 1122,
        "Urine": 0,
        "address": "",
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "",
        "id": 27,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 11,
        "ESR": 0,
        "Plasma": 0,
        "SST": 1122,
        "Urine": 0,
        "address": "",
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "",
        "id": 28,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 11,
        "ESR": 0,
        "Plasma": 0,
        "SST": 1122,
        "Urine": 0,
        "address": "",
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "",
        "id": 29,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 11,
        "ESR": 0,
        "Plasma": 0,
        "SST": 1122,
        "Urine": 0,
        "address": "",
        "big_box": null,
        "client_id": 1500,
        "client_practice_name": "Arizona Digestive Health",
        "comments": "",
        "id": 30,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 11,
        "ESR": 0,
        "Plasma": 0,
        "SST": 1122,
        "Urine": 0,
        "address": "",
        "big_box": null,
        "client_id": 1500,
        "client_practice_name": "Arizona Digestive Health",
        "comments": "",
        "id": 31,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 11,
        "ESR": 0,
        "Plasma": 0,
        "SST": 33,
        "Urine": 0,
        "address": "",
        "big_box": null,
        "client_id": 1500,
        "client_practice_name": "Arizona Digestive Health",
        "comments": "",
        "id": 32,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    },
    {
        "EDTA": 111111,
        "ESR": 11,
        "Plasma": 1111,
        "SST": 77,
        "Urine": 11,
        "address": "",
        "big_box": null,
        "client_id": 1111,
        "client_practice_name": "Research Gastroenterology",
        "comments": "",
        "id": 33,
        "operator": null,
        "patient_kit": null,
        "processed_by": null,
        "processed_time": "",
        "regular_box": null,
        "req": null,
        "shipping_method": "Ground",
        "time": ""
    }
];

export default client_pending_table;